
# Salvos de la Iglesia del planeta Tierra -  Desde Adán hasta El Trono Blanco. Apoc. 20:12

Continuamos nuestro recorrido escatológico y nos ubicamos en la tierra habitada desde Adam 1Cor 15:45 primera parte.  Podríamos decir de Adam el primer hombre caído en la tierra, narrado en la biblia Gen 3:6, aunque dejamos la ventana abierta si hay salvos antes de Adam.

Nos enfocaremos en ese recorrido desde Adam hasta hoy Julio 2019 la biblia nos ensena una sorprendente señal de todos los salvos, me refiero a la señal que le ensenaron al apóstol Juan en Patmos que se encuentra en apoca 12:1-2 en ella nos indica todos los salvos desde que hay memoria de lo escrito a la luz de la biblia en el c0nocimiento histórico de la biblia desde Génesis hasta apocalipsis.

En esta señal de una representación de tres grupos de salvos de toda de las. tres grandes dispensaciones o eras que nos marca la Biblia.

La mujer, vestida de sol, con la luna bajo sus pies, con las estrellas en su cabeza y la mujer misma embarazada representa los salvos de todos los tiempos del planeta tierra desde que hay conocimiento escrito bíblico.

•	Grupo numero uno, mujer vestida de sol= a salvos de la era de la gracia
•	Segundo grupo, la luna bajo de los pies = salvos de la era de la ley 
•	Tercer grupo, doce estrellas sobre su cabeza = salvos de la era patriarcal
•	Cuarto grupo, el embarazo o niño varón de la mujer vestido de sol, este grupo es de la era de la gracia que se enamoraron de Cristo, Cant .2:5 -Cant 5:8. Y fueron elegidos por la consagración que practicaron al nivel mas alto en la iglesia de Jesucristo hacer parte de niño varón de ese embarazo y que la biblia lo llama primicias. Apo 14:4

Este grupo que seria un subgrupo de los salvos de la gracias o sea la mujer vestida de sol, mueve a todos los salvos de la gracia por los dolores de parto de los cuales se encuentra en la actualidad Ap 12:2.

