baseurl = "https://vigorous-mirzakhani-bf2ecc.netlify.com/"
title = "Doctrina Elim"
theme = "hugo-universal-theme"
languageCode = "es-es"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"
# Enable comments by entering your Disqus shortname
disqusShortname = "omargonzalesdiaz"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-54695178-1"
